// Generated by `npm run gen:types` (supabase gen types typescript --local).
// Placeholder until the `links` schema exists, then regenerated against the live schema.
// eslint-ignored + coverage-excluded by convention (it's machine output, not hand-authored logic).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
