// The test law: every TypeScript source file ships a co-located
// *.test.ts(x) — `foo.ts` is satisfied by `foo.test.ts` or a qualified
// `foo.<aspect>.test.ts` beside it. Pure re-export barrels are exempt by detection;
// everything else skipped must be written down in EXEMPT with a reason. CI runs this
// after the unit suites (`npm run test:structure`).

import { readdirSync, readFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { pathToFileURL } from "node:url";

/** Explicit exemptions — every entry carries its excuse. */
export const EXEMPT: ReadonlyArray<{ path: string; reason: string }> = [
  { path: "apps/web/src/main.tsx", reason: "DOM bootstrap; the E2E suite boots it for real" },
  { path: "packages/model/src/database.types.ts", reason: "generated by supabase gen types" },
  { path: "packages/model/src/types.ts", reason: "pure type declarations, no runtime" },
];

export interface SourceFile {
  /** workspace-relative path with forward slashes */
  path: string;
  content: string;
}

/** A module whose every statement re-exports from elsewhere has no behavior of its own. */
export function isBarrel(content: string): boolean {
  const code = content
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith("//"));
  if (code.length === 0) return false;
  const statements = code
    .join(" ")
    .split(";")
    .map((s) => s.trim())
    .filter(Boolean);
  return statements.every(
    (s) =>
      /^export\s+(type\s+)?\{[^}]*\}\s+from\s+["'][^"']+["']$/.test(s) ||
      /^export\s+\*\s+from\s+["'][^"']+["']$/.test(s),
  );
}

function isTestFile(path: string): boolean {
  return /\.test\.tsx?$/.test(path);
}

function isSourceFile(path: string): boolean {
  return /\.tsx?$/.test(path) && !isTestFile(path) && !path.endsWith(".d.ts");
}

/** `dir/foo.ts` is covered by `dir/foo.test.ts(x)` or `dir/foo.<aspect>.test.ts(x)`. */
export function hasSiblingTest(path: string, all: ReadonlySet<string>): boolean {
  const m = /^(.*?)([^/]+)\.tsx?$/.exec(path);
  if (!m) return false;
  /* v8 ignore next 2 — groups exist when the regex matches; noUncheckedIndexedAccess appeasement */
  const dir = m[1] ?? "";
  const name = m[2] ?? "";
  const candidate = new RegExp(
    `^${escapeRegExp(dir)}${escapeRegExp(name)}(\\.[\\w-]+)?\\.test\\.tsx?$`,
  );
  for (const other of all) {
    if (candidate.test(other)) return true;
  }
  return false;
}

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function violations(files: ReadonlyArray<SourceFile>): string[] {
  const paths = new Set(files.map((f) => f.path));
  const exempt = new Set(EXEMPT.map((e) => e.path));
  const out: string[] = [];
  for (const file of files) {
    if (!isSourceFile(file.path)) continue;
    if (exempt.has(file.path)) continue;
    if (isBarrel(file.content)) continue;
    if (!hasSiblingTest(file.path, paths)) out.push(file.path);
  }
  return out.sort();
}

/* v8 ignore start — the walker is filesystem glue; the law itself is tested above */
const SKIP_DIRS = new Set([
  "node_modules",
  "dist",
  "coverage",
  "styled-system",
  "test-results",
  "playwright-report",
]);

function walk(root: string, dir: string, into: SourceFile[]): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (!SKIP_DIRS.has(entry.name)) walk(root, full, into);
    } else if (/\.tsx?$/.test(entry.name)) {
      into.push({
        path: relative(root, full).split(sep).join("/"),
        content: readFileSync(full, "utf8"),
      });
    }
  }
}

function main(): void {
  const root = process.cwd();
  const workspaces = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
    workspaces: string[];
  };
  const files: SourceFile[] = [];
  for (const pattern of workspaces.workspaces) {
    const base = pattern.replace(/\/\*$/, "");
    for (const entry of readdirSync(join(root, base), { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const src = join(root, base, entry.name, "src");
      try {
        walk(root, src, files);
      } catch {
        // workspace without src/ — nothing to check
      }
    }
  }
  walk(root, join(root, "scripts"), files);

  const missing = violations(files);
  if (missing.length > 0) {
    console.error("The test law: every TypeScript file ships a co-located test. Missing:\n");
    for (const path of missing) console.error(`  ${path}`);
    console.error(
      "\nWrite the test, or add an EXEMPT entry with its excuse (scripts/check-colocated-tests.ts).",
    );
    process.exit(1);
  }
  console.log(
    `test law: ${files.filter((f) => isSourceFile(f.path)).length} source files checked, all covered.`,
  );
}

// run only when executed directly (vitest imports the pure functions above)
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) main();
/* v8 ignore stop */
